name: Dummy Commit

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write # Ensure the workflow can write to the repository

jobs:
  dummy_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "abdelaziz.allem@gmail.com"
          git config --global user.name "Abdelaziz Allem"

      - name: Make a dummy change
        run: |
          # Append the current timestamp to README.md
          echo "Update at $(date)" >> README.md

      - name: Pull changes
        run: |
          git pull origin main

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Dummy commit for GitHub contributions" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:main
